### ISSUE TITLE
Неверный текст сообщения об ошибке на экране Регистрации

### ISSUE THREAD

**Issue by NataliaSusikova** [recruitment-process/recruitment-process-frontend#36]
**Предусловие:**
Открыть https://recruitment-process.github.io/recruitment-process-frontend/#/register
Перейти на экран Регистрации

**Шаги:**
Нажать на кнопку Зарегистрироваться

**ФР:** Контур поля ввода красный, текст сообщения об ошибке "Это поле должно быть заполнено"

**ОР:** Контур поля ввода остается черным, текст сообщения об ошибке "Укажите почту в формате [username@user.ru](mailto:username@user.ru)"

**Окружение:**
macOS Ventura версия 13.5
Safari v.16.6 (18615.3.12.11.2) разрешение экрана 1920х1080

<img width="522" alt="Сообщение об ошибке" src="https://github.com/recruitment-process/recruitment-process-frontend/assets/139118057/68a71340-3ddd-44a7-b574-28cb72c7bf77">

**Comment by Bjorn86** [comment]
@NataliaSusikova 
- В соответствии с UI-kit поле должно быть рамка поля ввода подсвечена при наличии ошибки
![image](https://github.com/recruitment-process/recruitment-process-frontend/assets/101380506/4874b1e2-a175-4cce-a2d3-83ef4d27d14d)
- В соответствии с макетом ошибка "Укажите почту в формате username@user.ru", появляется после начала ввода текста в поле, и свидетельствует о некорректности ввода.
![image](https://github.com/recruitment-process/recruitment-process-frontend/assets/101380506/fc70cc9e-5de6-41b0-9bb2-fece79808f20)
Ошибка "Это поле должно быть заполнено" относится к другому сценарию, не указанному в макете, когда поле является обязательным для заполнения но не заполнено. Это необходимо чтобы предотвратить отправку формы с пустыми данными.

**Comment by Bjorn86** [comment]
@NataliaSusikova тест уведомлений

**Comment by NataliaSusikova** [comment]
уточни, а ошибки должны выдаваться "после начала ввода текста в поле" или же при снятии фокуса в поле?

**Comment by NataliaSusikova** [comment]
<img width="475" alt="Снимок экрана 2023-08-07 в 21 48 46" src="https://github.com/recruitment-process/recruitment-process-frontend/assets/139118057/e84a251b-fd73-450c-b0a7-f00a0f7fab00">

Поменяешь? Тебе задачку ставить или здесь хватит обсуждения?

**Comment by NataliaSusikova** [comment]
<img width="1043" alt="Снимок экрана 2023-08-08 в 11 23 25" src="https://github.com/recruitment-process/recruitment-process-frontend/assets/139118057/106a9638-e5b6-4426-9198-7d0c86181071">

Пока оставляем текст, что в фигме.
Потом дизайнеры доработают еще подсказки под ограничения. Но когда – не ясно )
