### ISSUE TITLE
⚛️ Создание компонентов для страниц Регистрации и Авторизации

### ISSUE THREAD

**Issue by Pavelsmcom** [recruitment-process/recruitment-process-frontend#4]
Если вы взяли компонент в работу, то прошу написать это напротив компонента (In work), добавить имя (Name) и добавить себя в Assignee:
- [x] #9 
- [x] Button - Done - Pavel
- [x] #8
- [x] Check-box - In Progress - Dmitry
- [x] Logo - To-Do - Dzhaneta

**Comment by Bjorn86** [comment]
Готов забрать Input

**Comment by dzhaneta** [comment]
беру лого

**Comment by AlekseiUsov** [comment]
Мне остался линк)
