### ISSUE TITLE
⚛️ Разобраться с авторизацией через сторонние сервисы

### ISSUE THREAD

**Issue by Pavelsmcom** [recruitment-process/recruitment-process-frontend#6]
- [x] Разобраться с авторизацией через Goggle - In Progress -Aleksey
 - [x] Разобраться с авторизацией через Yandex - In Progress - Pavel
 - [ ] Разобраться с авторизацией через Vk - Progress - Name

Решили убрать этот функционал - задача отменена.

**Comment by gorbanalex** [comment]
Все процессы на Павле?

**Comment by AlekseiUsov** [comment]
Паша ты эту таску делаешь?

**Comment by Pavelsmcom** [comment]
Я только 1 процесс взял, Алексей ещё 1. Остался ещё Vk
